# -*- coding: utf-8 -*-
"""atividade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9f_X6F2BARrRvru0LoAYABtmzlIziRS

# **MÓDULO 25 - Operações Básicas SQL**

Para nossa atividade inicial de SQL trabalharemos com uma base de vendas.
Abaixo temos o ambiente de preparo para trabalharmos com o SQL lite.
"""

import sqlite3 #Importando a biblioteca necessária
import pandas as pd

from google.colab import files
uploaded = files.upload()

df_vendas = pd.read_csv("TB_VENDAS_TAREFA.csv", delimiter=';')

conn = sqlite3.connect(':memory:')
df_vendas.to_sql('tb_vendas', conn, index=False, if_exists='replace')

def run_query(query):
    return pd.read_sql_query(query, conn)

"""# 1) Faça uma consulta que retorne os nomes dos produtos distintos que temos na base de venda.

"""

query = """
SELECT DISTINCT PRODUTO

FROM tb_vendas

"""
result_df = run_query(query)
print(result_df)

"""# 2) Faça uma consulta que retorne a contagem dos clientes distintos que temos na nossa base, não esqueça de renomear sua coluna.

Dica: Você pode usar o distinct dentro do count()
"""

query = """
SELECT DISTINCT(count(ID_CLIENTE)) AS ContagemClientes

FROM tb_vendas

"""
result_df = run_query(query)
print(result_df)

"""# 3) Faça uma consulta que retorne uma coluna com os produtos distintos e o valor_unid de cada produto. Porém apenas para produtos onde o valor_unid é maior ou igual a 50 reais."""

query = """
SELECT DISTINCT PRODUTO,
      VALOR_UNID

FROM tb_vendas

WHERE VALOR_UNID >= 50

"""
result_df = run_query(query)
print(result_df)

"""# [DESAFIO] 4) Faça uma consulta que retorne o ID das compras e o valor total gasto nessa compra (Valor_unidade X Unidades) das 5 compras com mais valor total gasto."""

query = """
SELECT ID_COMPRA,
        (VALOR_UNID * UNIDADES) AS TOTALGASTO

FROM tb_vendas

ORDER BY TOTALGASTO DESC

LIMIT 5

"""
result_df = run_query(query)
print(result_df)

"""# 5) Faça uma consulta que retorne os produtos e a média do preço da unidade dos produtos, ordenando do maior para o menor."""

query = """
SELECT PRODUTO,
        avg(VALOR_UNID) AS MediaPreco

FROM tb_vendas

GROUP BY PRODUTO

ORDER BY MediaPreco DESC
"""
result_df = run_query(query)
print(result_df)

"""# 6) Faça uma consulta que retorne o id dos 3 clientes da base de vendas que mais relalizaram compras e a quantidade de compras realizadas."""

query = """
SELECT ID_CLIENTE,
      count(*) AS QuantidadeCompras

FROM tb_vendas

GROUP BY ID_CLIENTE

ORDER BY QuantidadeCompras DESC

LIMIT 3

"""
result_df = run_query(query)
print(result_df)